# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "projvar"
version = "0.5.1"
authors = ["Robin Vobruba <hoijui.quaero@gmail.com>"]
description = """
    A tiny CLI tool that tries to gather project specific meta-data in different ways,
    to store them into environment variables in a file
    for later use by other tools.
    See --list for the keys set by this tool.
    """
license = "GPL-3.0-or-later"
repository = "https://github.com/hoijui/repvar"
keywords = ["cli", "ci"]
categories = ["command-line-utilities", "text-processing"]
edition = "2018"

[dependencies]
anyhow = "1"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
# Until this is merged, we have to use the pull-requesters- version:
# https://gitlab.com/KonradBorowski/enum-map/-/merge_requests/40
#enum-map = "1.1.1"
enum-map = { git = "https://gitlab.com/bit_network/enum-map.git", branch = "impl_fromiter" }
git2 = "0.13"
human-panic = "1.0.3"
log = "0.4.14"
regex = "1.5"
remain = "0.2.2"
repvar = { git = "https://github.com/hoijui/repvar.git" }
simplelog = "0.10.0"
spdx = "0.6.2"
strum = "0.21"
strum_macros = "0.21"
#enumset = "1.0.7"
thiserror = "1"
url = "2.2.2"
