# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: build
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/build.yml'
  release:
    types: [ published ]
jobs:
  push_to_registry:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: REUSE - Fetch tool and BoM
        uses: fsfe/reuse-action@v1
        with:
          args: spdx
      - name: REUSE - Add the tools bin dir to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: "Get the Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: "Smart caching for rust/cargo"
        uses: Swatinem/rust-cache@v1

      - name: "Build"
        run: scripts/build

      - name: "Test & Check"
        run: scripts/test

